language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/android@sha256:3dd3e673d8045e9af17bc5bf72585768da12d44b05e2e51aff00ae17229a595d /bin/sh -c "cd /ga && ./gradlew lintProductionRelease && ./gradlew assembleProductionRelease"
    - os: osx
      osx_image: xcode8.3
      env:
        - ANDROID_HOME=/Users/travis/opt
        - SDK_FILENAME=sdk-tools-darwin-4333796.zip
        - HOMEBREW_NO_AUTO_UPDATE=1
      install:
        - mkdir -p $HOME/opt && curl -sSO https://dl.google.com/android/repository/${SDK_FILENAME} && unzip -qq ${SDK_FILENAME} -d $HOME/opt &> /dev/null
        - brew install gnu-sed &> /dev/null
        - yes | $HOME/opt/tools/bin/sdkmanager "tools" "platform-tools" &> /dev/null
        - yes | $HOME/opt/tools/bin/sdkmanager "build-tools;30.0.3" &> /dev/null
        - yes | $HOME/opt/tools/bin/sdkmanager "platforms;android-30" &> /dev/null
      script:
        - export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
        - ./gradlew lintProductionRelease
        - ./gradlew assembleProductionRelease
