language: generic
sudo: required
matrix:
  include:
    - services:
        - docker
      script: docker run -v $PWD:/ga greenaddress/android@sha256:c00c98afd6682d9a8e18917e75d1cfca24fa3b9575a783a9abaec826d8b23964 /bin/sh -c "cd /ga && ./gradlew --project-dir=bitcoinj/tools build && ./gradlew lintProductionRelease && ./gradlew assembleProductionRelease"
    - os: osx
      osx_image: xcode8.3
      env:
        - ANDROID_HOME=/Users/travis/opt
        - SDK_FILENAME=sdk-tools-darwin-4333796.zip
        - HOMEBREW_NO_AUTO_UPDATE=1
      install:
        - mkdir -p $HOME/opt && curl -sSO https://dl.google.com/android/repository/${SDK_FILENAME} && unzip -qq ${SDK_FILENAME} -d $HOME/opt &> /dev/null
        - brew install gnu-sed &> /dev/null
        - yes | $HOME/opt/tools/bin/sdkmanager "tools" "platform-tools" &> /dev/null
        - yes | $HOME/opt/tools/bin/sdkmanager "build-tools;30.0.3" &> /dev/null
        - yes | $HOME/opt/tools/bin/sdkmanager "platforms;android-30" &> /dev/null
      script:
        - export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
        - ./gradlew lintProductionRelease
        - ./gradlew assembleProductionRelease
